import _DownIcon from "./down";
import _ChevronBackIcon from "./back";
import _MailIcon from "./mail";
import _UserIcon from "./user";
import _PhoneIcon from "./phone";
import _SuccessIcon from "./successIcon";
import _FailIcon from "./fail";
import _ClockIcon from "./clock";
export const DownIcon = _DownIcon;
export const ChevronBackIcon = _ChevronBackIcon;
export const MailIcon = _MailIcon;
export const UserIcon = _UserIcon;
export const PhoneIcon = _PhoneIcon;
export const SuccessIcon = _SuccessIcon;
export const FailIcon = _FailIcon;
export const ClockIcon = _ClockIcon;
